spring:
  application:
    name: metricpoller

logging:
  level:
    org.springframework.web: DEBUG

job:
  cron:
    expression: "*/5 * * * * *"

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #instance Id dynamically set to allow multiple instances
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

elasticsearch:
  host: localhost
  port: 9200

metricpoller:
  endpoints: /admin/health, /admin/metrics, /admin/info
  index:
    #This has to match with the index template
    name: microsvcmetrics
    #using something else than Y,M,D can result in unexpected behavior on the naming of indices
    dateFormat: yyyy-MM-dd
